-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, p.PRICE*SUM(o.SALES_AMOUNT) as SALES
FROM PRODUCT as P
INNER JOIN OFFLINE_SALE as O
on P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC,PRODUCT_CODE