-- 코드를 입력하세요
SELECT a.TITLE,b.BOARD_ID,b.REPLY_ID,b.WRITER_ID,b.CONTENTS,date_format(b.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD as a
INNER JOIN USED_GOODS_REPLY as b
ON a.BOARD_ID = b.BOARD_ID
where a.CREATED_DATE like '%2022-10%'
order by b.CREATED_DATE,a.TITLE